---
title: "Experimental Design Notes"
subtitle: "(MATH 326)"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    code_folding: hide
    css: "styles.css"
---
<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
 
 function openTab(evt, tabName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
}
 
</script>


***

### Textbook 

[Math 326 Notebook Link Here!](https://byuistats.github.io/Math326_Quarto4/)

***

### Cheat Sheets

* [R Colors](http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf)

* [RStudio Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/)

* [R Base Commands Cheat Sheet](https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf)

* [Keyboard Shortcuts](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts)

***



### Don't forget to always load your libraries and to Knit often!!

```{r, message=FALSE, warning=FALSE}
library(mosaic)
library(tidyverse)
library(pander)
library(DT)
library(ggrepel)
library(plotly)
library(dplyr)
library(ggplot2)
library(maps)
library(tmap)
library(leaflet)
library(htmltools)
library(car)
library(mosaicData)
library(ResourceSelection)
library(reshape2)
library(RColorBrewer)
library(scatterplot3d)
library(readr)
library(prettydoc)
library(knitr)
library(kableExtra)
library(formattable)
library(haven)

```

***



This is the templet for the Hover Box Thingy

<a href="javascript:showhide('SampleHover')">
<div class="hoverchunk">
<span class="tooltipr">
Hover over words box!
  <span class="tooltiprtext">
  [insert description here]
  </span></span><span class="tooltipr">
&nbsp;&nbsp;&nbsp;&nbsp;  
</span><span class="tooltipr" style="float:right;">
&nbsp;...&nbsp; 
  <span class="tooltiprtext">Click to View Output.</span>
</span>
</div>
</a>
<div id="SampleHover" style="display:none;">

There are three parts to the help box: 

(1) <u>The starter code</u>

< a href="javascript:showhide('[**Insert classifying name**]')">
< div class="hoverchunk" >


<br>

(2) <u>The description code</u>
- This is the pattern of the reoccurring code that you need to look out for when writing in the help box descriptions! 

< span class="tooltipr" >
[**What shows up in the box**]
  < span class="tooltiprtext" >
  [**The description that shows up when you hover**]
  < /span>< /span >
  
<br>

(3) <u>The ending code</u>
- the r chunk you put right after will then show up after you click the help box!

& nbsp;& nbsp;& nbsp;& nbsp;  
< span class="tooltiprtext" >Press Enter to run the code. </span >
< /span><span class="tooltipr" style="float:right;" >
& nbsp;...& nbsp; 
  < span class="tooltiprtext" >Click to View Output.< /span >
< /span >
< /div >
< /a >
< div id="[**The classifying name that you put in the starter code!**]" style="display:none;" >

*When using, make sure you fix all the spaces when using and use "< /div >" to show where the drop down is meant to end! 

<br>


</div>

<br>

***


# Personal Notes

<br>

OoOoooOOOoo let's go assignments!!



<br>

***

## Weekly Assignments

<br>

The sections below show the different Skill Quizzes and Class Activities done throughout the semester. 
As well as some personal notes on those assignments!
</div>
 

<br>

***

### Week 1 | Welcome to the Course & Introduction to RStudio

<br>

***

#### Class Activity - Introduction to Basic Principles

**The 8 Key Principles of Experimental Design**

1. Understand the objectives of your research. What questions should be answered?
2. Determine the measurements that will be needed to help answer the questions of interest.
3. Determine which variables, which we will call factors, are the sources of variation in the measurements. Determine which of these factors you will be testing and decide which levels of those factors will be included in the study. Determine which of these factors you will hold constant.
4. Determine how sampling and treatment assignments will be done and then collect the data.
5. Identify the analysis technique that will be applied, including how to test hypotheses
6. Describe the data using numerical and graphical summaries.
7. Perform the analysis and make sure that the analysis is appropriate.
8. Make conclusions.

<br>


**Observational studies**: the researchers do not control the conditions of the study

**Designed experiments**: are studies in which the researchers control the conditions in which the study is performed

<br>

**5 Research Objectives**

1. Specific : 

2. Measurable

3. Achievable

4. Relevant

5. Time-based 

<br>

**4 Types of Measurement Scales:**

1. Nominal :  have no quantitative value and have no particular order. Gender and color are examples of nominal measurements
  - ex. gender and color

2. Ordinal : similar to the nominal variable, except that the categories fall in a significant and meaningful order
  - ex. rating on a good, great, bad scale

3. Interval : measurements are quantitative with a meaningful notion of distance between values, however zero does not have a true zero value
  - Ex. temperature measured in Fahrenheit or time measured in minutes

4. Ratio : measurements are also quantitative with a meaningful notion of distance between values and zero does have a true zero value
 - Ex. distance, length, weight, height


<br>

**Validity vs. Reliability**


Validity: the degree a study or a measure actually represents what it claims to represent
- ex. if the response varible for an experiement was a person's arithmetic skills we would need to carefully decide how that could be meausred

Reliability: the measure will give the same value as a reponse if it is used in identical conditions
- ex. meausring hand length in the same measurement unit

<br>

**Experiemental Units vs. Oberservation Units**

Experimental Units: 

Observational Units: 


<br>

**Example Scenario**

City leaders in a large city want to determine the most effective way to lower crime that occurs in the many city parks. They decide to test the effects of increased police patrols and increased lighting.

*The 8 Key Principles Application:*

1. What question do we want to answer?
- How is the amount of crime that occurs effected my police partols and increased lighting?

2. What measurements are we gonna take?
  - Crime citizens have reported (not police)

3. What factors can affect the measurements?
  - Lightening and Police Patrol

4. How would you sample this data?
  - Filming, taking shifts looking around for crime (not a smart idea)

5. What kind of analysis?
  - Two way ANOVA (two factors)

*6, 7, and 8 can be done with actual data!*


